name: raseed
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^13.0.0
  go_router: ^13.2.0
  riverpod: ^3.0.0
  image_picker: ^1.0.0
  google_wallet: ^0.1.2
  just_audio: ^0.9.36
  record: ^5.0.4
  speech_to_text: ^6.5.1
  url_launcher: ^6.2.6
  http: ^1.2.1
  path_provider: ^2.1.2
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
